name: simple_deploy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  archive: ^4.0.7
  dartssh2: ^2.13.0
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  shadcn_flutter: ^0.0.47
  uuid: ^4.5.2
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
